### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/buttons-and-scissors-activity#6]

**Comment by iamutkarshtiwari** [comment]
https://github.com/sugarlabs/buttons-and-scissors-activity/commit/f9aa15144647b333b5d169c28af35795db8e9aa0

**Comment by yell0wfl4sh** [comment]
92678b2f9d3a1a0e0de0495d199a5c7084498e11

I think this issue can now be closed.
