### ISSUE TITLE
Unwanted images and sounds in the project

### ISSUE THREAD

**Issue by DipanshKhandelwal** [sugarlabs/buttons-and-scissors-activity#8]
Some images and sounds are never being used.

**Comment by DipanshKhandelwal** [comment]
PR #9 .

**Comment by quozl** [comment]
Don't forget to close issues.

You can close them automatically by adding "fixes #number" to the commit message or pull request.

**Comment by DipanshKhandelwal** [comment]
@quozl ok thanks :+1:

**Comment by DipanshKhandelwal** [comment]
fixed by #9
